### PR TITLE
Add PR template (issue#199)

### PR DESCRIPTION
**Pull request by bkktimber**
# Add PR Template
 
 ## Description

Issue: [Add PR templates](https://github.com/blackjax-devs/blackjax/issues/199)
PR: [PR#230](https://github.com/blackjax-devs/blackjax/pull/230)

 ## Before Submitting

 - [x] If this PR is Typo or Documentation improvement, you can dismiss other checks
 - [ ] Title and Description are clear and comprehensible enough for anyone to understand the changes in this PR
 - [ ] PR Branch is rebased on the latest `main` commit
 - [ ] Consider opening a **Draft PR** if you would like some feedback from other contributors.
 - [ ] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
 - [ ] `pre-commit` should be installed and run before pushing to the branch
 - [ ] Make sure there are tests covering the changes
 - [ ] Consider adding/updating related [examples](https://github.com/blackjax-devs/blackjax/tree/main/examples)

### CODE REVIEW

**Comment by rlouf** [comment]
Thank you for contributing! This is a good start, and here is what I'd like people to check before they submit their PR:

0. Your first point
1. Branch is rebased on the latest `main` commit;
2. A description title; A high-level description of the change; Relevant issues, discussions and PRs are linked in the description
3. If the PR is not ready for review but would like some feedback you can open a draft PR
4. Make sure that commit messages follow these guidelines: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html;
5. `pre-commit` should be installed and run before pushing to the branch;
6. There should be tests covering the changes;
7. Your point on examples

(we unfortunately don't have contributing guidelines, so this essentially will be for now)

**Comment by bkktimber** [comment]
Thank you @rlouf for your comment. I updated the PR template and made another commit.

**Comment by rlouf** [comment]
Thank you, this looks almost perfect now! Should be ready to merge after addressing my comments.

**Comment by bkktimber** [comment]
I Updated both the PR template and comment. Please let me know if there is anything I missed from your comment.

Thank you.

**Comment by rlouf** [comment]
@bkktimber Merging now. Thank you for this very valuable contribution!

**Pull request merged**
