### PR TITLE
Handle references using sphinxcontrib-bibtex with the BibTeX alpha style

### LINKED ISSUE #493: Handle references better in the documentation
The current way citations are handled in the docstrings lead to multiple "duplicate citation" warnings since Sphinx handles reference globally. We need to handle references more carefully.

Sources:
- https://chiplicity.readthedocs.io/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html
- https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html

### PR DESCRIPTION
**Pull request by albcab**
Closes  #493.

### CODE REVIEW

**Comment by rlouf** [comment]
This looks good! However you will have to solve all the merge conflicts that appeared after the other documentation PR was merged.

**Comment by albcab** [comment]
Done! A bit easier to cite now.

**Comment by rlouf** [comment]
Does it render properly in the documentation?

**Comment by albcab** [comment]
Doesn't render properly yet, needs some revision.

**Comment by albcab** [comment]
It renders properly now. 

Sphinx builds the bibliography globally, so local reference blocks are difficult. Couldn't find a sensible solution to having local reference blocks so I created a new toctree with Bibliography where all the references link to (including the URLs).

**Comment by rlouf** [comment]
Amazing!

**Pull request merged**
