### PR TITLE
Coupled HMC methods

### PR DESCRIPTION
**Pull request by AdrienCorenflos**
This is a first crack at implementing coupled Markov chains as per this issue.

https://github.com/blackjax-devs/blackjax/issues/64

Apart from a big clean-up it will also require implementing Glynn-Rhee types of expectations estimates in order to effectively remove the MCMC bias. See essentially 2.3 in https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssb.12336 for the "easy" version for MH.

### CODE REVIEW

**Comment by AdrienCorenflos** [comment]
I need to have a good think about refactoring to be able to reuse HMC primitives more.

**Comment by AdrienCorenflos** [comment]
That was a bit harder than I expected but I think I'm fairly close to a prototype (though I'd rather we finished the SMC method before getting excited by this :D)

**Comment by AdrienCorenflos** [comment]
Note that I have modified a number of core functions to make them reusable for my purpose, so this will probably need a review in terms of library coherence from you @rlouf

**Comment by rlouf** [comment]
Can't you get the simpler coupling with HMC work just by sharing the same `rng_key` between the two kernels ?

**Comment by rlouf** [comment]
That would make a great addition ! We should aim to make this as simple as possible and re-use as much code as possible:

- For the HMC version, we can call the same `hmc` kernel with the same `rng_key` twice. We should make this usable with any kernel in the HMC family, and create a `HMCKernel` type so users downstream get a warning if trying to use it with a different kind of kernl. We can see the coupling procedure as a higher-level kernel that takes a primitive kernel and builds a new one.
- RWMH is a good addition, better implemented in a separate PR

**Comment by AdrienCorenflos** [comment]
I don't think that is gonna do. I'm also setting my eyes on the NUTS
equivalent which is slightly more complex and requires thinner handling of
the internals of the integrator.

**Comment by rlouf** [comment]
Ok! I'll let you do your thing while I work on the SMC PR 🙂

**Comment by AdrienCorenflos** [comment]
Yeah I probably overcomplicated it. The coupled RWMH though needs a very
specific max coupling and can't really be done the same way (the reflected
one happens to be the most efficient and easy implementation of it). But I
do think that I will make the biased coupled hmc disappear somehow.

**Comment by AdrienCorenflos** [comment]
I'll have a go at this a bit more this end of week I think. Please feel free to send suggestions on impl my way in the meantime though. I am not claiming to understand it fully. I literally read the papers I'm citing over breakfast a few months back, so I may make it more convoluted that it needs to be (or too simple too!).
There is some code that was made public by @pierrejacob too, but sadly it is in R and I genuinely can't read R, so I'm coding from the (very well written) paper only. Maybe when we are done here we can somewhat find a way to compare with the original implementation somehow.

**Comment by rlouf** [comment]
From what I've read, there are 3 different algorithms and 1 estimator that you would want to implement here:
1. Coupled RWMH
2. Coupled HMC (basically running two chains with the same rng key)
3. Something that couples HMC and RWMH

Here's how I would go about it:
- First implement (in this PR) coupled HMC + the estimator since it is the easiest;
- While you're at it implement in a next PR the other algorithm in #38 (COUPLED-ANTITHETIC)
- Implement RWMH in its own PR so we can design it carefully
- Implement coupled RWMH
- And finally couple HMC and RWMH

That should be enough work for the next few weeks :)

**Comment by pierrejacob** [comment]
Hi all,

I am very pleased to see your interest in these methods! Let me know if you think I can be helpful in any way. Happy to chat about any of this at least.

P

**Comment by AdrienCorenflos** [comment]
> Hi all,
> 
> I am very pleased to see your interest in these methods! Let me know if you think I can be helpful in any way. Happy to chat about any of this at least.
> 
> P

Hi!

I guess when I'm kinda done with the implementation (probably a few weeks) it would be good if you could step in to help with designing sanity checks/unittests, etc. 
In the meantime you can also shout at me if you see anything wrong in the thread!

**Comment by rlouf** [comment]
Hey - what's the status on this ?

**Comment by AdrienCorenflos** [comment]
I think I got the initial design wrong. We probably should have a chat, as
I am not sure what a good api would be. This is essentially a meta mcmc
algorithm, as it has an underlying stopping time that needs to be respected
(thereby is not adapted to the "give the user a kernel and let them use it"
paradigm). I have most of the logics blocks mind you, but we should have a
proper think about the desired API.

Le jeu. 23 sept. 2021 à 13:00, Rémi Louf ***@***.***> a
écrit :

**Comment by rlouf** [comment]
Ok let's add that to the meeting's agenda then.

**Comment by rlouf** [comment]
@AdrienCorenflos should we close this, open one issue per algorithm and work on the design there?

**Pull request closed without merging**
