### PR TITLE
add preconditioning matrix to barker proposal

### PR DESCRIPTION
**Pull request by ismael-mendoza**
# Overview

This PR attempts to add a preconditioning matrix to the barker proposal implementation, as in appendix G of https://arxiv.org/abs/1908.11812

- Relevant discussion #723 
- Relevant issue #725 

# Discussion / Questions
- Not sure if this is the best way to take the sqrt of the inverse mass matrix? I redo the computation of the inverse twice (tried to follow HMC but didn't seem appropriate to create a metric)
- Do I need to update the PDF? (not used anywhere in the codebase)
- I added `step_size` and the `inverse_mass_matrix` to the BarkerState (didnt' have any of these before), OK? 
- It's not very clear in the Barker paper but the step_size (sigma) is a 'global scale' and the inverse mass matrix is separate. Are these redundant? See implementation from authors here (in R) - https://github.com/gzanella/barker/blob/master/functions.R

# Thank you for opening a PR!

 A few important guidelines and requirements before we can merge your PR:

 - [x] *If I add a new sampler*, there is an issue discussing it already;
 - [x] We should be able to understand what the PR does from its title only;
 - [ ] There is a high-level description of the changes;
 - [x] There are links to *all* the relevant issues, discussions and PRs;
 - [x] The branch is rebased on the latest `main` commit;
 - [ ] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html);
 - [ ] The code respects the current naming conventions;
 - [ ] Docstrings follow the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html)
 - [ ] `pre-commit` is installed and configured on your machine, and you ran it before opening the PR;
 - [ ] There are tests covering the changes;
 - [ ] The doc is up-to-date;
 - [x] *If I add a new sampler** I added/updated related [examples](https://github.com/blackjax-devs/blackjax/tree/main/examples)

Consider opening a **Draft PR** if your work is still in progress but you would like some feedback from other contributors.

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
Closing because I jsut read the guidelines and noticed the commit and pre-commit requirements

**Comment by AdrienCorenflos** [comment]
Nw -> the commit pre-commit stuff is only last stage. In the meantime you can just try to get the logic right and then ask for a review when you think you have the Lego pieces fitting together.

**Comment by AdrienCorenflos** [comment]
Feel free to open a new pr or reopen this one, at the end of the day it doesn't matter much.

**Comment by ismael-mendoza** [comment]
Thanks @AdrienCorenflos that makes sense, I'll open a new one but remember that for next time. For reference opened #731

**Pull request closed without merging**
