### PR TITLE
Build docs in PR and clean workflows

### LINKED ISSUE #294: Test doc building in CI
Builds often fail, and this failure should not happen after merging on `main`.

### PR DESCRIPTION
**Pull request by rlouf**
In this PR I allow the CI to build docs on PRs, and do some light cleaning of the workflow files. Closes #294

### CODE REVIEW

**Comment by rlouf** [comment]
Waiting for the build to complete to see if we can catch errors.

**Comment by rlouf** [comment]
Waiting for #277 to be merged to rebase and check that CI passes.

**Comment by junpenglao** [comment]
BTW, now that we are building docs on each PR, could we parse the run time and use it as additional benchmark/regression test?

**Comment by rlouf** [comment]
That's a good idea although I'd rather we focus our efforts on #163.

**Pull request merged**
