### PR TITLE
create bayesian logistic regression notebook demo

### PR DESCRIPTION
**Pull request by gerdm**
# Bayesian logistic regression
* Notebook implementing Bayesian logistic regression using the RWMH sampler from BlackJAX

(This is a work in progress)

## To-do
- [ ] Add comments
- [ ] Document code

### CODE REVIEW

**Comment by gerdm** [comment]
Please comment / give feedback on the demo. Thanks!

**Comment by gerdm** [comment]
I'm cc'ing @murphyk who might be able to give valuable comments.

**Comment by rlouf** [comment]
Is this ready for review ?

**Comment by murphyk** [comment]
@gerdm  This is ready for review, right? (Although it may be more interesting to use HMC kernel than RWMH :)

**Comment by gerdm** [comment]
Yes. This is ready.

**Comment by gerdm** [comment]
Thanks for the comments @rlouf. I'll work on them.

**Comment by canyon289** [comment]
@rlouf I would advise not adding a dependency for sklearn in `requirements.txt`. This means that anyone who just wants to use the blackjax libs will need to install a fairly heavyweight dependency, even if they have no intention of running this notebook.

I suggest that a `requirements-docs.txt` or the like be created. This will be needed anyway once blackjax starts compiling docs

https://github.com/arviz-devs/arviz/blob/main/requirements-docs.txt

**Comment by rlouf** [comment]
You mean like https://github.com/blackjax-devs/blackjax/blob/main/notebooks/requirements.txt ?

**Comment by canyon289** [comment]
> You mean like https://github.com/blackjax-devs/blackjax/blob/main/notebooks/requirements.txt ?
> 
> In this case I would only add a `!pip install sklearn` cell.

Made a PR here. Can discuss there not to clutter this one if you'd like :) https://github.com/blackjax-devs/blackjax/pull/124

**Comment by rlouf** [comment]
@gerdm mind that `rwmh` is called `rmh` since #130.

**Comment by gerdm** [comment]
Thanks for the heads up @rlouf. I'll make the changes accordingly

**Comment by rlouf** [comment]
@gerdm ping

**Comment by rlouf** [comment]
I made the changes @gerdm, thank you for contributing!

**Pull request merged**
