### PR TITLE
Create GOVERNANCE.md

### PR DESCRIPTION
**Pull request by OriolAbril**
Add the contents from https://github.com/blackjax-devs/blackjax/issues/28 as governance file

 A few important guidelines and requirements before we can merge your PR:

 - [x] We should be able to understand what the PR does from its title only;
 - [x] There is a high-level description of the changes;
 - [x] There are links to *all* the relevant issues, discussions and PRs;
 - [x] The branch is rebased on the latest `main` commit;
 - [x] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html); (I think)

### CODE REVIEW

**Comment by junpenglao** [comment]
Yeah I am not sure what GOVERNANCE would serve in this case, since both me and Remi does not have a lot of bandwidth to maintain a community, there is essentially nothing to govern.

I suggest we delay this until somebody express a strong interest to join the core developer team (with number of PR contributions to back it up)

**Comment by OriolAbril** [comment]
Would you be open to other people joining the core team though? Would maintaining a community around blackjax be something valuable to you/the project?

The same way the governance can be 2 lines if that is all it is it can also say "we won't maintain any community and community contributions won't be considered for joining the project", or "the project members are @rlouf and @junpenglao and there are no plans to let anyone else join". 

Otherwise, I think even if they were interested it is close to impossible for anyone else to dedicate enough time to have enough PRs to show for and trigger the discussion unless they know one of you personally and they can get more info on how many PRs or how big a PR, or even some guarantees the effort won't be in vain.

There is nothing wrong with any approach, it is only a matter of setting the expectations of potential contributors if you want any to exist.

**Comment by junpenglao** [comment]
Thanks for raising this @OriolAbril I think there are a lot to think about. We will follow best practices depending on the needs when the time comes.

**Comment by rlouf** [comment]
+1 @junpenglao

**Pull request closed without merging**
