### PR TITLE
Added example of how to run on PyMC3 models

### PR DESCRIPTION
**Pull request by kc611**
This PR simply adds the notebook from #27.

### CODE REVIEW

**Comment by rlouf** [comment]
Looks good to me. Can you add a header with `Author:` and your name before merging ?

**Comment by twiecki** [comment]
This is great! I think it would be better to use the same model as from the other examples, so that we can also do speed comparisons. That can also be done in addition to the one here, but it doesn't seem to converge well.

**Comment by rlouf** [comment]
@kc611 Do you need any help with this?

**Comment by kc611** [comment]
Hey, sorry for (very) late response, got caught up in other stuff. I built the recommended 8-schools model in https://colab.research.google.com/drive/1lUXPRynGCuusHLpBTnC1tPw-2zw_6NwG?usp=sharing and ran into that strange error over there, I think it's due to the runtime environment (the code runs locally). Can you please confirm that ?

Also where do I add the Author header you mentioned ?

**Comment by rlouf** [comment]
Indeed it runs locally so it must be an environment issue. Just add `Author: <your name>` under the title, it should do. Let me know and I'll merge.

**Comment by rlouf** [comment]
Merging. Thank you for contributing!

**Pull request merged**
