### PR TITLE
Fix SMC notebook as per issue https://github.com/blackjax-devs/blackjax/issues/148

### PR DESCRIPTION
**Pull request by AdrienCorenflos**

### CODE REVIEW

**Comment by AdrienCorenflos** [comment]
https://github.com/blackjax-devs/blackjax/issues/148

**Comment by AdrienCorenflos** [comment]
Urgh... Again the end of line in notebooks...

**Comment by rlouf** [comment]
I know but I can't merge before that's fixed somehow.

**Comment by AdrienCorenflos** [comment]
But the end of file is here right? Or am I completely wrong so as to what the style checker calls an end of line?

image

**Comment by rlouf** [comment]
I'm not sure what's happening with your setup, but `pre-commit` removed the empty lines and everything was fine when I ran it again.

**Pull request merged**
