### PR TITLE
Resolve: Add progress bar to run_inference_algorithm

### LINKED ISSUE #610: Add progress bar to `run_inference_loop`
We now have a `run_inference_loop` implemented in [here](https://github.com/blackjax-devs/blackjax/pull/598), adding a progress bar would be nice and quite straightforward (see eg: https://github.com/pymc-devs/pymc/commit/c3f93bad3db7c34c12e4c51e1e7fb88f62c97020)

### PR DESCRIPTION
**Pull request by PaulScemama**
Closes #610. Adds progress bar to `run_inference_algorithm`. 

 A few important guidelines and requirements before we can merge your PR:

 - [ ] *If I add a new sampler*, there is an issue discussing it already;
 - [x] We should be able to understand what the PR does from its title only;
 - [x] There is a high-level description of the changes;
 - [x] There are links to *all* the relevant issues, discussions and PRs;
 - [x] The branch is rebased on the latest `main` commit;
 - [x] Commit messages follow these [guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html);
 - [x] The code respects the current naming conventions;
 - [x] Docstrings follow the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html)
 - [x] `pre-commit` is installed and configured on your machine, and you ran it before opening the PR;
 - [ ] There are tests covering the changes;
 - [ ] The doc is up-to-date;
 - [ ] *If I add a new sampler** I added/updated related [examples](https://github.com/blackjax-devs/blackjax/tree/main/examples)

Consider opening a **Draft PR** if your work is still in progress but you would like some feedback from other contributors.

### CODE REVIEW

**Review by junpenglao — CHANGES_REQUESTED** [review]
Add a kwarg that default to False, similar to https://github.com/blackjax-devs/blackjax/blob/540db419f0ccddb0368443049492b6c0448fe273/blackjax/adaptation/window_adaptation.py#L251

**Comment by PaulScemama** [comment]
@junpenglao I am trying to figure out why some of the tests are failing. Also, should I adapt some tests to use the progress_bar?

**Review by junpenglao — APPROVED** [review]

**Comment by junpenglao** [comment]
Looks like there is a flaky test - could you change the rng_key of that test until it pass, and add a comment that it is a flaky test?

**Comment by junpenglao** [comment]
@reubenharry found a bug in the function, cause by this line: https://github.com/blackjax-devs/blackjax/blob/540db419f0ccddb0368443049492b6c0448fe273/blackjax/util.py#L174

Could you remove this line and add a test? Something like:
```python
import jax
import jax.numpy as jnp
from blackjax.mcmc.hmc import hmc
from blackjax.util import run_inference_algorithm

def logdensity_fn(x):
    return -0.5 * jnp.sum(jnp.square(x))

alg = hmc(
    logdensity_fn=logdensity_fn,
    inverse_mass_matrix=jnp.eye(2),
    step_size=1.0,
    num_integration_steps=1000,
)

_ = run_inference_algorithm(
    rng_key=jax.random.PRNGKey(0),
    initial_state_or_position=jnp.array([1.0, 1.0]),
    inference_algorithm=alg,
    num_steps=10,
    progress_bar=True)
```

**Comment by PaulScemama** [comment]
@junpenglao I think you meant to tag me instead of @reubenharry? But yes definitely!, sorry about that.

**Comment by junpenglao** [comment]
test_util.py sounds good.

**Comment by PaulScemama** [comment]
@junpenglao I have to step away for the rest of the day. Just added a test for `run_inference_loop` but haven't done anything with the flaky tests yet. I'll be back tomorrow. Thanks for all the help!

**Review by junpenglao — APPROVED** [review]

**Comment by junpenglao** [comment]
The flaky test is not failing now, so I am going to go ahead and merge it. Thanks!

**Pull request merged**
