### PR TITLE
Add introduction notebook

### PR DESCRIPTION
**Pull request by canyon289**
Adding a very basic introduction notebook. Going to add some more explanatory text and figures to make this easier to read in the coming days.

Feel free to make any suggestions to spice this up some or any other ideas you'd like to see.

### CODE REVIEW

**Comment by rlouf** [comment]
Thanks for setting this up! I will edit it as we go, switching to a draft PR until it is ready for review.

**Comment by canyon289** [comment]
Added some more words. I think this is good enough for now and we can expand as the library expands

**Comment by rlouf** [comment]
Indeed that's good enough for
now, thanks! Merging.

**Comment by canyon289** [comment]
Thanks buddy!

**Pull request merged**
